# This file was generated by GoReleaser. DO NOT EDIT.
cask "darght" do
  name "darght"
  desc "Theme detection CLI"
  homepage "https://github.com/sebakri/darght"
  version "0.2.7"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "darght"

  on_macos do
    on_intel do
      url "https://github.com/sebakri/darght/releases/download/v#{version}/darght_#{version}_darwin_amd64.tar.gz",
        verified: "github.com/sebakri/darght"
      sha256 "9d6b77d8c6b3dec13264e6cb59188b2ad72a5e3fc5e261fbd38fdc1bfe9d00dd"
    end
    on_arm do
      url "https://github.com/sebakri/darght/releases/download/v#{version}/darght_#{version}_darwin_arm64.tar.gz",
        verified: "github.com/sebakri/darght"
      sha256 "3993a15da40b8dc8c1a64e625f5e1b6e4f7f71963cee3d270b7f00180e8f7e40"
    end
  end

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/darght"]
    end
  end

  # No zap stanza required
end
